title: a decidophobia
logo: /assets/img/coffee.jpg
description: >-
    an android developer that
    use arch linux and
    love to procrastinate
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
    - jekyll-archives
jekyll-arhives:
    enabled: []
    layout: 'archive'
    permalinks:
        year: '/year/'
        month: '/:year/:month/'
        day: '/:year/:month/:day/'
        tag: '/tag/:name/'
        category: '/category/:name/'
