title: a decidophobia
logo: /assets/img/coffee.jpg
description: >-
    an android developer that
    use arch linux and
    love to procrastinate
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
