title: hendratay
logo: /assets/img/joker.jpg
description: >-
    an android developer and a backend developer.
    You can learn more about me at <a href="/about">about</a>.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
    - jekyll-archives
jekyll-arhives:
    enabled: []
    layout: 'archive'
    permalinks:
        year: '/year/'
        month: '/:year/:month/'
        day: '/:year/:month/:day/'
        tag: '/tag/:name/'
        category: '/category/:name/'
